# Generated by Django 5.2.3 on 2025-06-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Título del servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icono (opcional, FontAwesome o Bootstrap Icon)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagen (opcional)')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio)')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
