# Generated by Django 5.2.3 on 2025-06-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_paymentlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoovConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Moov', help_text='Nombre de referencia de esta configuración', max_length=100)),
                ('username', models.CharField(help_text='Moov public key (username)', max_length=255)),
                ('password', models.CharField(help_text='Moov private key (password)', max_length=255)),
                ('account_id', models.CharField(help_text='Account ID principal', max_length=255)),
                ('partner_account_id', models.CharField(help_text='Partner Account ID', max_length=255)),
                ('merchant_payment_method_id', models.CharField(help_text='Merchant Payment Method ID', max_length=255)),
                ('client_id', models.CharField(blank=True, help_text='Client ID OAuth', max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, help_text='Client Secret OAuth', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, help_text='Marca si esta configuración está activa')),
            ],
            options={
                'verbose_name': 'Configuración Moov',
                'verbose_name_plural': 'Configuraciones Moov',
            },
        ),
    ]
