# Generated by Django 5.2.3 on 2025-07-02 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_moovconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('dui', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('enviado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
            },
        ),
        migrations.CreateModel(
            name='Transaccion3DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTarjeta', models.CharField(max_length=150)),
                ('mesVencimiento', models.CharField(max_length=50)),
                ('anioVencimiento', models.CharField(max_length=50)),
                ('cvv', models.CharField(max_length=50)),
                ('monto', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='wompi_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(blank=True, max_length=800, null=True)),
                ('client_id', models.TextField(blank=True, max_length=800, null=True)),
                ('client_secret', models.TextField(blank=True, max_length=800, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración Wompi',
                'verbose_name_plural': 'Configuraciones Wompi',
            },
        ),
        migrations.CreateModel(
            name='Transaccion3DS_Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTransaccion', models.CharField(max_length=150)),
                ('esReal', models.BooleanField(default=True)),
                ('urlCompletarPago3Ds', models.URLField(max_length=500)),
                ('monto', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('transaccion3ds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion3ds_respuesta_set', to='home.transaccion3ds')),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionCompra3DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('transaccion3ds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion3ds_set', to='home.transaccion3ds')),
                ('transaccion3ds_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion3ds_respuesta_set', to='home.transaccion3ds_respuesta')),
            ],
        ),
    ]
