# Generated by Django 5.2.3 on 2025-07-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_clientes_contactmessage_transaccion3ds_wompi_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoovBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('tipo_empresa', models.CharField(help_text='Ej: llc, corporation, sole-proprietor', max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('pais', models.CharField(default='US', max_length=2)),
                ('moov_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
