# Generated by Django 5.2.3 on 2025-07-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_moovbusinessaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moovbusinessaccount',
            old_name='direccion',
            new_name='accepted_user_agent',
        ),
        migrations.RenameField(
            model_name='moovbusinessaccount',
            old_name='pais',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='moovbusinessaccount',
            old_name='nombre_empresa',
            new_name='legal_name',
        ),
        migrations.RenameField(
            model_name='moovbusinessaccount',
            old_name='codigo_postal',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='moovbusinessaccount',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='moovbusinessaccount',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='moovbusinessaccount',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='moovbusinessaccount',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='moovbusinessaccount',
            name='tipo_empresa',
        ),
        migrations.AddField(
            model_name='moovbusinessaccount',
            name='accepted_date',
            field=models.DateTimeField(default="2025-07-02 20:17:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moovbusinessaccount',
            name='accepted_ip',
            field=models.GenericIPAddressField(default="192.168.2.0"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moovbusinessaccount',
            name='address_line1',
            field=models.CharField(default="111", max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moovbusinessaccount',
            name='address_line2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='moovbusinessaccount',
            name='city',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moovbusinessaccount',
            name='ein_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moovbusinessaccount',
            name='postal_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moovbusinessaccount',
            name='state',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moovbusinessaccount',
            name='website',
            field=models.URLField(default="http://example.com"),
            preserve_default=False,
        ),
    ]
