"""
Django settings for homeasis project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@__qv)*_=3n-9py0)crfc3($zshn+@h#qlwx$54xm(@+_a)6uk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS=['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'tailwind',
    #'theme',  # vamos a crear este app
]

#TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = [
    "127.0.0.1",
]


ALLOWED_HOSTS = [
    'xsoporte.incoe.cloud',
    '127.0.0.1:8000',
    '127.0.0.1',
    '192.168.2.49',
    '192.168.1.40',
    'xsoporte.contaspro.cloud'
]

CSRF_TRUSTED_ORIGINS = [
    "https://xsoporte.incoe.cloud",
    "http://xsoporte.incoe.cloud",
    "https://xsoporte.contaspro.cloud",
    "http://xsoporte.contaspro.cloud",
    "https://192.168.1.40:8686",
    "http://192.168.1.40:8686",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'homeasis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'homeasis.wsgi.application'

# Cbn3OsIQSqRyQ_Uk
# HY_H-mtzRBPkcbcxRThfvdszPM7mV2_I

# settings.py
MOOV_USERNAME = "WEGidQgYRt77Sb3Y"
MOOV_PASSWORD = "nzDaL-20IEDvImiZjQYC_qRxgcSCchSZ"
MOOV_ACCOUNT_ID = "26d9e511-59d1-4217-bf4a-0d8c79539efd"  # ejemplo
MOOV_PARTNER_ACCOUNT_ID = "26d9e511-59d1-4217-bf4a-0d8c79539efd"
MOOV_MERCHANT_PAYMENT_METHOD_ID = "33eacac9-3294-4848-8dfd-f107ca03f58f"

MOOV_CLIENT_ID = "WEGidQgYRt77Sb3Y"
MOOV_CLIENT_SECRET = "nzDaL-20IEDvImiZjQYC_qRxgcSCchSZ"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# Configuración regional para El Salvador
LANGUAGE_CODE = 'es-SV'
TIME_ZONE = 'America/El_Salvador'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Configuración de archivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


